Repository team401/2023-Robot-Code, pull requests merged in 2023-10, with the labels that each got.

#26 Robot relative drive
  src/main/java/frc/robot/RobotContainer.java
Labels: enhancement

#27 Add functional balance auto
  src/main/deploy/pathplanner/B-1-2.path
  src/main/java/frc/robot/commands/auto/AutoRoutines.java
  src/main/java/frc/robot/commands/auto/Balance.java
  src/main/java/frc/robot/subsystems/drive/Drive.java
  src/main/java/frc/robot/subsystems/vision/Camera.java
Labels: autonomous

#28 Update cone placement setpoint
  src/main/java/frc/robot/Constants.java
Labels: bug
